#!/bin/bash
COMMAND="C:\Program Files\SecondLife\SLVoice.exe"

echo "===================================================================="
echo "Launching voice"
echo "===================================================================="
echo Arguments: "$@"

wine "$COMMAND" "$@"
if [ "$?" != "0" ] ; then 
	echo Failed to run voice
	exit 1
fi

echo Voice loaded
