#!/sbin/runscript
PIDFILE=/var/run/tor/ocat.pid
LOGFILE=/var/log/ocatd.log

depend() {
	need net tor
}

start() {
	ebegin "Starting Ocat daemon..."
	start-stop-daemon --start --pidfile "${PIDFILE}" --quiet --exec /usr/bin/ocat -- -C -4 -L ${LOGFILE} -u tor $(cat /var/lib/tor/ocat/hostname) &> /dev/null
	eend $?
}

stop() {
	ebegin "Stopping Ocat daemon..."
	start-stop-daemon --stop --quiet --pidfile "${PIDFILE}" 
}

